# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  test-php7.4:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.4-cli
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install FS packages
          command: |
            sudo apt-get update && sudo apt-get install -y libuv1-dev libevent-dev libssl-dev

      - run: 
          name: Install LibUV
          command: |
            sudo pecl install channel://pecl.php.net/uv-0.2.4
            sudo docker-php-ext-enable uv
            php -i | grep uv

      - run:
          name: Install Ev
          command: |
            sudo pecl install ev
            sudo docker-php-ext-enable ev
            php -i | grep ev

      - run:
          name: Install event
          command: |
            sudo docker-php-ext-install sockets
            sudo pecl install event
            sudo docker-php-ext-enable event
            php -i | grep event

      - run:
          name: Install LibEvent
          command: |
            mkdir ~/lib
            cd ~/lib
            sudo git clone https://github.com/expressif/pecl-event-libevent.git
            cd pecl-event-libevent
            sudo phpize
            sudo ./configure
            sudo make
            sudo make install
            sudo docker-php-ext-enable libevent

      - run: 
          name: Install packages using composer
          command: | 
            composer install

      - run:
          name: Run tests
          command: |
            php ./vendor/bin/pest --coverage-clover coverage.xml

      - run:
          name: Upload coverage report to codecov.io
          command: |
            bash <(curl -s https://codecov.io/bash)


workflows:
  version: 2
  test:
    jobs:
      - test-php7.4
