# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  test-php7.4-libuv:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.4-cli
    working_directory: ~/project
    steps:
      - checkout
      - run: 
          name: Install LibUV
          command: |
            sudo apt-get update && sudo apt-get install -y libuv-dev

      - run: 
          name: Install packages using composer
          command: | 
            composer install
      - run:
          name: Run tests
          command: |
            php ./vendor/bin/pest

workflows:
  version: 2
  test:
    jobs:
      - test-php7.4-libuv
